# Generated by Django 5.1.3 on 2024-11-30 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100, null=True)),
                ('registration_deadline', models.DateTimeField(null=True)),
                ('banner', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('registration_limit', models.IntegerField(default=-1)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_api.usermodel')),
            ],
        ),
    ]
