# Generated by Django 5.1.3 on 2024-11-30 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api', '0002_eventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_api.usermodel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_api.eventmodel')),
            ],
        ),
    ]
