# Generated by Django 5.1.3 on 2024-11-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_api', '0003_registrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrations',
            new_name='RegistrationsModel',
        ),
    ]
